name: Deploy to Remote Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate SSH key
      run: |
        ssh-keygen -t ed25519 -C "conecsa@conecsa.com.br" -f ~/.ssh/id_ed25519 -N ""
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key to the agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Copy SSH key to remote host
      run: |
        ssh-keyscan -H conecsa.com.br >> ~/.ssh/known_hosts
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh-copy-id -i ~/.ssh/id_ed25519.pub conecsa@conecsa.com.br

    - name: Create Docker context
      run: |
        docker context create remote --docker "host=ssh://conecsa@conecsa.com.br"

    - name: Deploy with Docker Compose V2
      run: |
        docker --context remote compose up -d

      env:
        CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
        DATABASE_SCHEMA: ${{ secrets.DATABASE_SCHEMA }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        FIRST_NAME: ${{ secrets.FIRST_NAME }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        LAST_NAME: ${{ secrets.LAST_NAME }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        REGISTER_NUMBER: ${{ secrets.REGISTER_NUMBER }}
        USERCODE: ${{ secrets.USERCODE }}
        USERNAME: ${{ secrets.USERNAME }}
